language: node_js

node_js:
  - node
  - lts/*
  - 6

sudo: false

branches:
  only:
    - master
    - dev

cache: yarn

before_install:
  # use newer version of yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

script:
  - yarn run test-ci
  - codecov
